/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CasinoExploreImport } from './routes/casino.explore'
import { Route as CasinoGameCodeImport } from './routes/casino.game.$code'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CasinoExploreRoute = CasinoExploreImport.update({
  path: '/casino/explore',
  getParentRoute: () => rootRoute,
} as any)

const CasinoGameCodeRoute = CasinoGameCodeImport.update({
  path: '/casino/game/$code',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/casino/explore': {
      preLoaderRoute: typeof CasinoExploreImport
      parentRoute: typeof rootRoute
    }
    '/casino/game/$code': {
      preLoaderRoute: typeof CasinoGameCodeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CasinoExploreRoute,
  CasinoGameCodeRoute,
])

/* prettier-ignore-end */
